export const appConfig = {
    API_URL: 'http://localhost:8000/',
    TOKEN_AUTH_PATH: 'api-token-auth/',
    CURRENT_USER_PATH: 'current-user/',
    LOGOUT_PATH: 'logout/',
    WEATHER_DATA_PATH: 'weather/weather-data/',
    TURKEY_CITIES: [
        { value: null, text: 'Please select a city' },
        {'value': 'Adana', 'text': 'Adana'},
        {'value': 'Adiyaman', 'text': 'Adıyaman'},
        {'value': 'Afyonkarahisar', 'text': 'Afyonkarahisar'},
        {'value': 'Agri Turkey', 'text': 'Ağrı'},
        {'value': 'Amasya', 'text': 'Amasya'},
        {'value': 'Ankara', 'text': 'Ankara'},
        {'value': 'Antalya', 'text': 'Antalya'},
        {'value': 'Artvin', 'text': 'Artvin'},
        {'value': 'Aydin', 'text': 'Aydın'},
        {'value': 'Balikesir', 'text': 'Balıkesir'},
        {'value': 'Bilecik', 'text': 'Bilecik'},
        {'value': 'Bingol Turkey', 'text': 'Bingöl'},
        {'value': 'Bitlis', 'text': 'Bitlis'},
        {'value': 'Bolu', 'text': 'Bolu'},
        {'value': 'Burdur', 'text': 'Burdur'},
        {'value': 'Bursa', 'text': 'Bursa'},
        {'value': 'Çanakkale', 'text': 'Çanakkale'},
        {'value': 'Cankiri', 'text': 'Çankırı'},
        {'value': 'Corum Turkey', 'text': 'Çorum'},
        {'value': 'Denizli', 'text': 'Denizli'},
        {'value': 'Diyarbakır', 'text': 'Diyarbakır'},
        {'value': 'Edirne', 'text': 'Edirne'},
        {'value': 'Elazığ', 'text': 'Elazığ'},
        {'value': 'Erzincan', 'text': 'Erzincan'},
        {'value': 'Erzurum', 'text': 'Erzurum'},
        {'value': 'Eskişehir', 'text': 'Eskişehir'},
        {'value': 'Gaziantep', 'text': 'Gaziantep'},
        {'value': 'Giresun', 'text': 'Giresun'},
        {'value': 'Gümüşhane', 'text': 'Gümüşhane'},
        {'value': 'Hakkari', 'text': 'Hakkari'},
        {'value': 'Hatay', 'text': 'Hatay'},
        {'value': 'Isparta', 'text': 'Isparta'},
        {'value': 'Mersin', 'text': 'Mersin'},
        {'value': 'İstanbul', 'text': 'İstanbul'},
        {'value': 'İzmir', 'text': 'İzmir'},
        {'value': 'Kars', 'text': 'Kars'},
        {'value': 'Kastamonu', 'text': 'Kastamonu'},
        {'value': 'Kayseri', 'text': 'Kayseri'},
        {'value': 'Kırklareli', 'text': 'Kırklareli'},
        {'value': 'Kırşehir', 'text': 'Kırşehir'},
        {'value': 'Kocaeli', 'text': 'Kocaeli'},
        {'value': 'Konya', 'text': 'Konya'},
        {'value': 'Kütahya', 'text': 'Kütahya'},
        {'value': 'Malatya', 'text': 'Malatya'},
        {'value': 'Manisa', 'text': 'Manisa'},
        {'value': 'Kahramanmaraş', 'text': 'Kahramanmaraş'},
        {'value': 'Mardin', 'text': 'Mardin'},
        {'value': 'Muğla', 'text': 'Muğla'},
        {'value': 'Muş', 'text': 'Muş'},
        {'value': 'Nevşehir', 'text': 'Nevşehir'},
        {'value': 'Niğde', 'text': 'Niğde'},
        {'value': 'Ordu', 'text': 'Ordu'},
        {'value': 'Rize', 'text': 'Rize'},
        {'value': 'Sakarya', 'text': 'Sakarya'},
        {'value': 'Samsun', 'text': 'Samsun'},
        {'value': 'Siirt', 'text': 'Siirt'},
        {'value': 'Sinop', 'text': 'Sinop'},
        {'value': 'Sivas', 'text': 'Sivas'},
        {'value': 'Tekirdağ', 'text': 'Tekirdağ'},
        {'value': 'Tokat', 'text': 'Tokat'},
        {'value': 'Trabzon', 'text': 'Trabzon'},
        {'value': 'Tunceli', 'text': 'Tunceli'},
        {'value': 'Sanliurfa', 'text': 'Şanlıurfa'},
        {'value': 'Uşak', 'text': 'Uşak'},
        {'value': 'Van', 'text': 'Van'},
        {'value': 'Yozgat', 'text': 'Yozgat'},
        {'value': 'Zonguldak', 'text': 'Zonguldak'},
        {'value': 'Aksaray', 'text': 'Aksaray'},
        {'value': 'Bayburt', 'text': 'Bayburt'},
        {'value': 'Karaman', 'text': 'Karaman'},
        {'value': 'Kırıkkale', 'text': 'Kırıkkale'},
        {'value': 'Batman', 'text': 'Batman'},
        {'value': 'Şırnak', 'text': 'Şırnak'},
        {'value': 'Bartin Turkey', 'text': 'Bartın'},
        {'value': 'Ardahan', 'text': 'Ardahan'},
        {'value': 'Iğdır', 'text': 'Iğdır'},
        {'value': 'Yalova', 'text': 'Yalova'},
        {'value': 'Karabük', 'text': 'Karabük'},
        {'value': 'Kilis', 'text': 'Kilis'},
        {'value': 'Osmaniye', 'text': 'Osmaniye'},
        {'value': 'Düzce', 'text': 'Düzce'}
    ]
}
